# Generated by Django 4.0.6 on 2022-07-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='colorurl',
            field=models.ImageField(upload_to='color/'),
        ),
    ]
